/*
 * Система рассмотрения заявок на экспресс-гарантии, полученных от партнеров банка
 *
 * Функционал выдачи экспресс гарантий позволяет реализовать след. сервисы:  - Создание клиентом заявки в личном кабинете на выдачу экспресс-гарантии - Отображение информации о закупке по минимальному набору введенных атрибутов - Загрузка и прикрепление документов к заявке - Формирование заявления на выдачу экспресс-гарантии для подписания клиентом - Подписание клиентом заявления с использованием УНЭП - Отображение в Интернет банке статусов заявки - Получение и передача заявок от партнеров - Создание сотрудником банка заявки на гарантию - Формирование проекта решения по заявке на гарантию
 *
 * The version of the OpenAPI document: 1.4.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;

namespace Multibanking.GuaranteeClient.Model
{
    /// <summary>
    ///     Зарпос для подтверждения загрузки документа из банка
    /// </summary>
    [DataContract(Name = "DownloadConfirmDto")]
    public class DownloadConfirmDto : IEquatable<DownloadConfirmDto>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="DownloadConfirmDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DownloadConfirmDto()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="DownloadConfirmDto" /> class.
        /// </summary>
        /// <param name="requestId">Идентификатор запроса (required).</param>
        public DownloadConfirmDto(string requestId = default)
        {
            // to ensure "requestId" is required (not null)
            if (requestId == null) throw new ArgumentNullException("requestId is a required property for DownloadConfirmDto and cannot be null");
            RequestId = requestId;
        }

        /// <summary>
        ///     Идентификатор запроса
        /// </summary>
        /// <value>Идентификатор запроса</value>
        [DataMember(Name = "requestId", IsRequired = true, EmitDefaultValue = true)]
        public string RequestId { get; set; }

        /// <summary>
        ///     Returns true if DownloadConfirmDto instances are equal
        /// </summary>
        /// <param name="input">Instance of DownloadConfirmDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DownloadConfirmDto input)
        {
            if (input == null) return false;
            return
                RequestId == input.RequestId ||
                (RequestId != null &&
                 RequestId.Equals(input.RequestId));
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            // RequestId (string) maxLength
            if (RequestId != null && RequestId.Length > 36) yield return new ValidationResult("Invalid value for RequestId, length must be less than 36.", new[] { "RequestId" });

            // RequestId (string) minLength
            if (RequestId != null && RequestId.Length < 36)
                yield return new ValidationResult("Invalid value for RequestId, length must be greater than 36.", new[] { "RequestId" });

            // RequestId (string) pattern
            var regexRequestId = new Regex(@"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", RegexOptions.CultureInvariant);
            if (false == regexRequestId.Match(RequestId).Success)
                yield return new ValidationResult("Invalid value for RequestId, must match a pattern of " + regexRequestId, new[] { "RequestId" });
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DownloadConfirmDto {\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as DownloadConfirmDto);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (RequestId != null) hashCode = hashCode * 59 + RequestId.GetHashCode();
                return hashCode;
            }
        }
    }
}