/*
 * Система рассмотрения заявок на экспресс-гарантии, полученных от партнеров банка
 *
 * Функционал выдачи экспресс гарантий позволяет реализовать след. сервисы:  - Создание клиентом заявки в личном кабинете на выдачу экспресс-гарантии - Отображение информации о закупке по минимальному набору введенных атрибутов - Загрузка и прикрепление документов к заявке - Формирование заявления на выдачу экспресс-гарантии для подписания клиентом - Подписание клиентом заявления с использованием УНЭП - Отображение в Интернет банке статусов заявки - Получение и передача заявок от партнеров - Создание сотрудником банка заявки на гарантию - Формирование проекта решения по заявке на гарантию
 *
 * The version of the OpenAPI document: 1.4.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Multibanking.GuaranteeClient.Model
{
    /// <summary>
    ///     Данные оферты
    /// </summary>
    [DataContract(Name = "PaglRequest")]
    public class PaglRequest : IEquatable<PaglRequest>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="PaglRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaglRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="PaglRequest" /> class.
        /// </summary>
        /// <param name="pagls">pagls (required).</param>
        public PaglRequest(List<PaglDto> pagls = default)
        {
            // to ensure "pagls" is required (not null)
            if (pagls == null) throw new ArgumentNullException("pagls is a required property for PaglRequest and cannot be null");
            Pagls = pagls;
        }

        /// <summary>
        ///     Gets or Sets Pagls
        /// </summary>
        [DataMember(Name = "pagls", IsRequired = true, EmitDefaultValue = true)]
        public List<PaglDto> Pagls { get; set; }

        /// <summary>
        ///     Returns true if PaglRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PaglRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaglRequest input)
        {
            if (input == null) return false;
            return
                Pagls == input.Pagls ||
                (Pagls != null &&
                 input.Pagls != null &&
                 Pagls.SequenceEqual(input.Pagls));
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaglRequest {\n");
            sb.Append("  Pagls: ").Append(Pagls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as PaglRequest);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Pagls != null) hashCode = hashCode * 59 + Pagls.GetHashCode();
                return hashCode;
            }
        }
    }
}