/*
 * Получение информации о счете клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по счетам и транзакциям.
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace Multibanking.AccountClient.Client;

/// <summary>
///     Http methods supported by swagger
/// </summary>
public enum HttpMethod
{
    /// <summary>HTTP GET request.</summary>
    Get,

    /// <summary>HTTP POST request.</summary>
    Post,

    /// <summary>HTTP PUT request.</summary>
    Put,

    /// <summary>HTTP DELETE request.</summary>
    Delete,

    /// <summary>HTTP HEAD request.</summary>
    Head,

    /// <summary>HTTP OPTIONS request.</summary>
    Options,

    /// <summary>HTTP PATCH request.</summary>
    Patch
}