using Multibanking.UnidentifiedPaymentClient.Api;

namespace Multibanking.Data.OpenAPIBankClients.UnidentifiedPaymentClient;

public class UnidentifiedPaymentClient : UnidentifiedPaymentsApi, IUnidentifiedPaymentClient;
