services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - keycloak
    ports:
      - 80:80
    networks:
      - backend-network

  api: 
    build: 
      context: ../
      dockerfile: ./Multibanking.Devops/api-dockerfile
    depends_on:
      - postgres_app 
      - keycloak
    expose:
      - "8080"
    networks:
      - backend-network
    env_file:
      - .env

  postgres_app:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin  
      DB_VENDOR: postgres
      DB_ADDR: postgres_keycloak  
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      KC_PROXY: edge
    ports:
      - 8080:8080
    networks:
      - backend-network
    depends_on:
      - postgres_keycloak
    command: start-dev 

  postgres_keycloak:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_USER: keycloak_user
      POSTGRES_DB: keycloak_db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
