using Multibanking.PeriodPaymentClient.Api;

namespace Multibanking.Data.OpenAPIBankClients.PeriodPaymentClient.Implementations;

public class PeriodPaymentConsentClient : PeriodPaymentConsentApi, IPeriodPaymentConsentClient;