/*
 * Получение информации о счете клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по счетам и транзакциям.
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Multibanking.AccountClient.Model;

/// <summary>
///     Подтип ресурса банковского счета
/// </summary>
/// <value>Подтип ресурса банковского счета</value>
[JsonConverter(typeof(StringEnumConverter))]
public enum AccountSubTypeStaticType
{
    /// <summary>
    ///     Enum CreditCard for value: CreditCard
    /// </summary>
    [EnumMember(Value = "CreditCard")] CreditCard = 1,

    /// <summary>
    ///     Enum CurrentAccount for value: CurrentAccount
    /// </summary>
    [EnumMember(Value = "CurrentAccount")] CurrentAccount = 2,

    /// <summary>
    ///     Enum Loan for value: Loan
    /// </summary>
    [EnumMember(Value = "Loan")] Loan = 3,

    /// <summary>
    ///     Enum Mortgage for value: Mortgage
    /// </summary>
    [EnumMember(Value = "Mortgage")] Mortgage = 4,

    /// <summary>
    ///     Enum PrePaidCard for value: PrePaidCard
    /// </summary>
    [EnumMember(Value = "PrePaidCard")] PrePaidCard = 5,

    /// <summary>
    ///     Enum Savings for value: Savings
    /// </summary>
    [EnumMember(Value = "Savings")] Savings = 6
}