/*
 * Получение информации о счете клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по счетам и транзакциям.
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Multibanking.AccountClient.Model;

/// <summary>
///     DataTransactionResponseComplexType
/// </summary>
[DataContract(Name = "DataTransactionResponseComplexType")]
public class DataTransactionResponseComplexType : IEquatable<DataTransactionResponseComplexType>,
    IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="DataTransactionResponseComplexType" /> class.
    /// </summary>
    /// <param name="transaction">transaction.</param>
    public DataTransactionResponseComplexType(Collection<TransactionComplex> transaction = default)
    {
        Transaction = transaction;
    }

    /// <summary>
    ///     Gets or Sets Transaction
    /// </summary>
    [DataMember(Name = "Transaction", EmitDefaultValue = false)]
    public Collection<TransactionComplex> Transaction { get; set; }

    /// <summary>
    ///     Returns true if DataTransactionResponseComplexType instances are equal
    /// </summary>
    /// <param name="input">Instance of DataTransactionResponseComplexType to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(DataTransactionResponseComplexType input)
    {
        if (input == null) return false;
        return
            Transaction == input.Transaction ||
            (Transaction != null &&
             input.Transaction != null &&
             Transaction.SequenceEqual(input.Transaction));
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class DataTransactionResponseComplexType {\n");
        sb.Append("  Transaction: ").Append(Transaction).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as DataTransactionResponseComplexType);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Transaction != null) hashCode = hashCode * 59 + Transaction.GetHashCode();
            return hashCode;
        }
    }
}