/*
 * Инициирование перевода денежных средств клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по переводам.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Multibanking.UnidentifiedPaymentClient.Model;

/// <summary>
///     Финансовая организация, обслуживающая счет получателя средств
/// </summary>
[DataContract(Name = "BranchAndFinancialInstitutionIdentificationComplexType")]
public class BranchAndFinancialInstitutionIdentificationComplexType : IEquatable<BranchAndFinancialInstitutionIdentificationComplexType>, IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="BranchAndFinancialInstitutionIdentificationComplexType" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected BranchAndFinancialInstitutionIdentificationComplexType()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="BranchAndFinancialInstitutionIdentificationComplexType" /> class.
    /// </summary>
    /// <param name="schemeName">БИК/SWIFT банка контрагента (required).</param>
    /// <param name="identification">БИК/SWIFT банка контрагента (required).</param>
    /// <param name="name">Наименование банка контрагента.</param>
    /// <param name="postalAddress">postalAddress.</param>
    public BranchAndFinancialInstitutionIdentificationComplexType(FinancialInstitutionIdentificationDynamicType schemeName = default, string identification = default,
        string name = default, PartyIdentificationCompexTypePostalAddress postalAddress = default)
    {
        SchemeName = schemeName;
        // to ensure "identification" is required (not null)
        if (identification == null)
            throw new ArgumentNullException("identification is a required property for BranchAndFinancialInstitutionIdentificationComplexType and cannot be null");
        Identification = identification;
        Name = name;
        PostalAddress = postalAddress;
    }

    /// <summary>
    ///     БИК/SWIFT банка контрагента
    /// </summary>
    /// <value>БИК/SWIFT банка контрагента</value>
    [DataMember(Name = "schemeName", IsRequired = true, EmitDefaultValue = true)]
    public FinancialInstitutionIdentificationDynamicType SchemeName { get; set; }

    /// <summary>
    ///     БИК/SWIFT банка контрагента
    /// </summary>
    /// <value>БИК/SWIFT банка контрагента</value>
    [DataMember(Name = "identification", IsRequired = true, EmitDefaultValue = true)]
    public string Identification { get; set; }

    /// <summary>
    ///     Наименование банка контрагента
    /// </summary>
    /// <value>Наименование банка контрагента</value>
    [DataMember(Name = "name", EmitDefaultValue = false)]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or Sets PostalAddress
    /// </summary>
    [DataMember(Name = "PostalAddress", EmitDefaultValue = false)]
    public PartyIdentificationCompexTypePostalAddress PostalAddress { get; set; }

    /// <summary>
    ///     Returns true if BranchAndFinancialInstitutionIdentificationComplexType instances are equal
    /// </summary>
    /// <param name="input">Instance of BranchAndFinancialInstitutionIdentificationComplexType to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(BranchAndFinancialInstitutionIdentificationComplexType input)
    {
        if (input == null) return false;
        return
            (
                SchemeName == input.SchemeName ||
                SchemeName.Equals(input.SchemeName)
            ) &&
            (
                Identification == input.Identification ||
                (Identification != null &&
                 Identification.Equals(input.Identification))
            ) &&
            (
                Name == input.Name ||
                (Name != null &&
                 Name.Equals(input.Name))
            ) &&
            (
                PostalAddress == input.PostalAddress ||
                (PostalAddress != null &&
                 PostalAddress.Equals(input.PostalAddress))
            );
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Identification (string) maxLength
        if (Identification != null && Identification.Length > 35)
            yield return new ValidationResult("Invalid value for Identification, length must be less than 35.", new[] { "Identification" });

        // Name (string) maxLength
        if (Name != null && Name.Length > 160) yield return new ValidationResult("Invalid value for Name, length must be less than 160.", new[] { "Name" });
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class BranchAndFinancialInstitutionIdentificationComplexType {\n");
        sb.Append("  SchemeName: ").Append(SchemeName).Append("\n");
        sb.Append("  Identification: ").Append(Identification).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  PostalAddress: ").Append(PostalAddress).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as BranchAndFinancialInstitutionIdentificationComplexType);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = hashCode * 59 + SchemeName.GetHashCode();
            if (Identification != null) hashCode = hashCode * 59 + Identification.GetHashCode();
            if (Name != null) hashCode = hashCode * 59 + Name.GetHashCode();
            if (PostalAddress != null) hashCode = hashCode * 59 + PostalAddress.GetHashCode();
            return hashCode;
        }
    }
}