/*
 * Инициирование перевода денежных средств клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по переводам.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Multibanking.UnidentifiedPaymentClient.Client.OpenAPIDateConverter;

namespace Multibanking.UnidentifiedPaymentClient.Model
{
    /// <summary>
    /// Сумма денег, подлежащая переводу между плательщиком и получателем до вычета комиссии, выраженная в валюте поручения инициатора.
    /// </summary>
    [DataContract(Name = "InitiationComplexType_InstructedAmount")]
    public partial class InitiationComplexTypeInstructedAmount : IEquatable<InitiationComplexTypeInstructedAmount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiationComplexTypeInstructedAmount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitiationComplexTypeInstructedAmount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiationComplexTypeInstructedAmount" /> class.
        /// </summary>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">Код валюты, соответствующий международного стандарта ISO 4217. (required).</param>
        public InitiationComplexTypeInstructedAmount(string amount = default(string), string currency = default(string))
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for InitiationComplexTypeInstructedAmount and cannot be null");
            }
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for InitiationComplexTypeInstructedAmount and cannot be null");
            }
            this.Currency = currency;
        }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// Код валюты, соответствующий международного стандарта ISO 4217.
        /// </summary>
        /// <value>Код валюты, соответствующий международного стандарта ISO 4217.</value>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitiationComplexTypeInstructedAmount {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InitiationComplexTypeInstructedAmount);
        }

        /// <summary>
        /// Returns true if InitiationComplexTypeInstructedAmount instances are equal
        /// </summary>
        /// <param name="input">Instance of InitiationComplexTypeInstructedAmount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InitiationComplexTypeInstructedAmount input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Amount != null)
                {
                    hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                }
                if (this.Currency != null)
                {
                    hashCode = (hashCode * 59) + this.Currency.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
