/*
 * Инициирование перевода денежных средств клиента третьей стороной
 *
 * Содержит описываются API для Открытых банковских интерфейсов по переводам.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Multibanking.UnidentifiedPaymentClient.Client.OpenAPIDateConverter;

namespace Multibanking.UnidentifiedPaymentClient.Model
{
    /// <summary>
    /// Defines TransactionStatusStaticType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionStatusStaticType
    {
        /// <summary>
        /// Enum AcceptedSettlementCompleted for value: AcceptedSettlementCompleted
        /// </summary>
        [EnumMember(Value = "AcceptedSettlementCompleted")]
        AcceptedSettlementCompleted = 1,

        /// <summary>
        /// Enum AcceptedSettlementInProcess for value: AcceptedSettlementInProcess
        /// </summary>
        [EnumMember(Value = "AcceptedSettlementInProcess")]
        AcceptedSettlementInProcess = 2,

        /// <summary>
        /// Enum Pending for value: Pending
        /// </summary>
        [EnumMember(Value = "Pending")]
        Pending = 3,

        /// <summary>
        /// Enum Rejected for value: Rejected
        /// </summary>
        [EnumMember(Value = "Rejected")]
        Rejected = 4,

        /// <summary>
        /// Enum AcceptedWithoutPosting for value: AcceptedWithoutPosting
        /// </summary>
        [EnumMember(Value = "AcceptedWithoutPosting")]
        AcceptedWithoutPosting = 5,

        /// <summary>
        /// Enum AcceptedCreditSettlementCompleted for value: AcceptedCreditSettlementCompleted
        /// </summary>
        [EnumMember(Value = "AcceptedCreditSettlementCompleted")]
        AcceptedCreditSettlementCompleted = 6

    }

}
