/*
 * Периодические  переводы денежных средств с переменными реквизитами
 *
 * Спецификация содержит описание элементов, которые являются общими для всех API на периодические  переводы денежных средств с переменными реквизитами (далее по тексту ППДС). В соответствии со стандартом ППДС Пользователь имеет право предоставить долгосрочное согласие на Услугу «Платежный сервис» СППУ с целью инициирования переводов средств от их имени, без необходимости аутентификации каждого отдельного платежа Пользователем у ППИУ. При этом ППИУ и СППУ реализуют взаимодействие для осуществления ППДС используя API.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Multibanking.PeriodPaymentClient.Model;

/// <summary>
///     Раздел Meta обязателен, но может быть пустым. Необязательный элемент - «TotalPages», указывает на количество передаваемых страниц. Если передается более одной страницы, то
///     элемент «TotalPages» обязательно присутствует.
/// </summary>
[DataContract(Name = "Meta")]
public class Meta : IEquatable<Meta>, IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="Meta" /> class.
    /// </summary>
    /// <param name="totalPages">Указывает на количество передаваемых страниц.</param>
    public Meta(int totalPages = default)
    {
        TotalPages = totalPages;
    }

    /// <summary>
    ///     Указывает на количество передаваемых страниц
    /// </summary>
    /// <value>Указывает на количество передаваемых страниц</value>
    [DataMember(Name = "totalPages", EmitDefaultValue = false)]
    public int TotalPages { get; set; }

    /// <summary>
    ///     Returns true if Meta instances are equal
    /// </summary>
    /// <param name="input">Instance of Meta to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Meta input)
    {
        if (input == null) return false;
        return
            TotalPages == input.TotalPages ||
            TotalPages.Equals(input.TotalPages);
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Meta {\n");
        sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as Meta);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = hashCode * 59 + TotalPages.GetHashCode();
            return hashCode;
        }
    }
}